import { createCanvas } from "@napi-rs/canvas";

export async function generateComparisonImage(
  title: string,
  products: Record<string, any>[]
): Promise<Buffer> {
  const displayProducts = products.slice(0, 3); // Max 3 products side-by-side
  const numProducts = displayProducts.length;

  const width = 1000;
  const headerHeight = 110;
  const rowHeight = 60;

  const rows = [
    { label: "Price", key: (p: any) => p.Price ?? p.price ?? "N/A" },
    { label: "Processor", key: (p: any) => p["Processor Name"] ?? p.Processor ?? "N/A" },
    { label: "RAM", key: (p: any) => p.RAM ?? "N/A" },
    { label: "Storage", key: (p: any) => p["SSD Capacity"] ?? p.SSD ?? "N/A" },
    { label: "Graphics", key: (p: any) => p["Graphic Processor"] ?? p.gpu ?? "N/A" },
    { label: "Display", key: (p: any) => (p["Screen Size"] ?? p.display ?? "15.6 Inch").substring(0, 20) },
    { label: "Best For", key: (p: any) => (p["Suitable For"] ?? p.type ?? "Multitasking").split(",")[0].substring(0, 20) },
  ];

  const footerHeight = 50;
  const height = headerHeight + (rows.length + 1) * rowHeight + footerHeight;

  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext("2d");

  // Dark slate background
  ctx.fillStyle = "#0F172A";
  ctx.fillRect(0, 0, width, height);

  // Gradient Header
  const gradient = ctx.createLinearGradient(0, 0, width, 0);
  gradient.addColorStop(0, "#2563EB"); // Blue
  gradient.addColorStop(1, "#7C3AED"); // Purple
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, width, headerHeight);

  // Header Text
  ctx.fillStyle = "#FFFFFF";
  ctx.font = "bold 26px sans-serif";
  ctx.fillText("⚡ LAPTOP SPECIFICATION COMPARISON", 30, 48);

  ctx.font = "18px sans-serif";
  ctx.fillStyle = "#E0E7FF";
  ctx.fillText(title.substring(0, 60), 30, 84);

  // Column Dimensions
  const featureColWidth = 220;
  const productColWidth = (width - featureColWidth - 40) / numProducts;

  // Header Row (Product Headers)
  let yPos = headerHeight;
  ctx.fillStyle = "#1E293B";
  ctx.fillRect(0, yPos, width, rowHeight);

  ctx.fillStyle = "#94A3B8";
  ctx.font = "bold 16px sans-serif";
  ctx.fillText("SPECIFICATION", 30, yPos + 38);

  const colors = ["#38BDF8", "#F43F5E", "#10B981"];

  displayProducts.forEach((p, idx) => {
    const xPos = featureColWidth + 20 + idx * productColWidth;
    const shortName = (p.Brand ?? p["Product Name"] ?? p.name ?? `Product ${idx + 1}`)
      .split(" ")
      .slice(0, 3)
      .join(" ")
      .substring(0, 22);

    ctx.fillStyle = colors[idx % colors.length];
    ctx.font = "bold 18px sans-serif";
    ctx.fillText(shortName, xPos + 10, yPos + 38);
  });

  // Border below header
  ctx.strokeStyle = "#334155";
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  ctx.moveTo(0, yPos + rowHeight);
  ctx.lineTo(width, yPos + rowHeight);
  ctx.stroke();

  yPos += rowHeight;

  // Data Rows
  rows.forEach((row, rowIdx) => {
    ctx.fillStyle = rowIdx % 2 === 0 ? "#0F172A" : "#1E293B";
    ctx.fillRect(0, yPos, width, rowHeight);

    ctx.fillStyle = "#94A3B8";
    ctx.font = "bold 16px sans-serif";
    ctx.fillText(row.label, 30, yPos + 36);

    displayProducts.forEach((p, idx) => {
      const xPos = featureColWidth + 20 + idx * productColWidth;
      const rawVal = String(row.key(p)).replace(".00", "").substring(0, 24);

      ctx.fillStyle = row.label === "Price" ? "#38BDF8" : "#F8FAFC";
      ctx.font = row.label === "Price" ? "bold 18px sans-serif" : "15px sans-serif";
      ctx.fillText(rawVal, xPos + 10, yPos + 36);
    });

    ctx.strokeStyle = "#334155";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(0, yPos + rowHeight);
    ctx.lineTo(width, yPos + rowHeight);
    ctx.stroke();

    yPos += rowHeight;
  });

  // Vertical Column Dividers
  ctx.strokeStyle = "#334155";
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  ctx.moveTo(featureColWidth + 10, headerHeight);
  ctx.lineTo(featureColWidth + 10, yPos);
  ctx.stroke();

  displayProducts.forEach((_, idx) => {
    if (idx < numProducts - 1) {
      const xPos = featureColWidth + 20 + (idx + 1) * productColWidth;
      ctx.beginPath();
      ctx.moveTo(xPos - 5, headerHeight);
      ctx.lineTo(xPos - 5, yPos);
      ctx.stroke();
    }
  });

  // Footer Bar
  ctx.fillStyle = "#0F172A";
  ctx.fillRect(0, yPos, width, footerHeight);

  ctx.fillStyle = "#64748B";
  ctx.font = "14px sans-serif";
  ctx.fillText("🤖 Generated by AI Assistant • Dynamic Specs Matrix", 30, yPos + 30);

  return canvas.toBuffer("image/png");
}
