/**
 * Only used to generate the AI "Which is Best?" recommendation paragraph.
 * The table is generated by buildComparisonTable() in the handler, not by the LLM.
 */
export function buildRecommendationPrompt(
  customerMessage: string,
  products: any[]
): string {

  const productSummaries = products.map((p, i) => {
    const name = p["Product Name"] ?? p.name ?? `Product ${i + 1}`;
    const price = String(p.Price ?? "N/A").replace(".00", "");
    const cpu = p["Processor Name"] ?? p.Processor ?? "N/A";
    const ram = p.RAM ?? "N/A";
    const ssd = p["SSD Capacity"] ?? p.SSD ?? "N/A";
    const gpu = p["Graphic Processor"] ?? p.gpu ?? "N/A";
    return `${i + 1}. ${name} | Price: ${price} | CPU: ${cpu} | RAM: ${ram} | Storage: ${ssd} | GPU: ${gpu}`;
  }).join("\n");

  return `
You are a professional laptop advisor on WhatsApp.

The customer asked: "${customerMessage}"

Here are the products being compared:
${productSummaries}

Your task:
- Write ONLY the "🏆 Which is Best?" recommendation section.
- Do NOT write a table. The table is already shown above your text.
- Keep the recommendation to 3-5 lines maximum.
- Recommend the best product for the customer's specific use case (e.g. multitasking, gaming, budget, everyday use).
- IMPORTANT DEMANDING TASKS/GAMING RULE: If the customer asks about running highly demanding modern games (such as GTA 6, Cyberpunk 2077, RDR 2, etc.) or intensive tasks, and all the compared laptops only have low-end or outdated GPUs (like GTX 1650, GTX 1650 Ti, or integrated graphics), you MUST explicitly warn them that these laptops are not powerful enough to run that game smoothly. Advise them to consider increasing their budget slightly (e.g. to ₹83,000+) to purchase a modern RTX series laptop (such as the MSI GF65 Thin with RTX 3060).
- Use single asterisks (*text*) for bold, not double asterisks (**text**).
- Never mention product IDs like LAP-0014. Use short friendly product names only.
- NEVER mention Meta, Meta AI, Google, Gemini, OpenAI, ChatGPT, Anthropic, Claude, Llama, or Groq. If asked about your identity, state only that you are the company's Laptop Assistant.
- End with: "Would you like more details on any of these laptops?"

Start your output with: 🏆 *Which is Best?*
`;
}

/** @deprecated Use buildRecommendationPrompt instead */
export function buildProductComparisonPrompt(
  customerMessage: string,
  products: any[]
): string {
  return buildRecommendationPrompt(customerMessage, products);
}